// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using tasinmazYonetimi.Data;

#nullable disable

namespace tasinmazYonetimi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("tasinmazYonetimi.Models.Il", b =>
                {
                    b.Property<int>("ilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ilId"));

                    b.Property<string>("ilAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ilId");

                    b.ToTable("Il");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Ilce", b =>
                {
                    b.Property<int>("ilceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ilceId"));

                    b.Property<int>("ilId")
                        .HasColumnType("integer");

                    b.Property<string>("ilceAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ilceId");

                    b.HasIndex("ilId");

                    b.ToTable("Ilce");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Kullanici", b =>
                {
                    b.Property<int>("kullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("kullaniciId"));

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("eMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("eklenmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("guncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("kullaniciAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("kullaniciSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("parola")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("kullaniciId");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Log", b =>
                {
                    b.Property<int>("logId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("logId"));

                    b.Property<string>("aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("islemTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("kullaniciId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("tarihSaat")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("logId");

                    b.HasIndex("kullaniciId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Mahalle", b =>
                {
                    b.Property<int>("mahalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("mahalleId"));

                    b.Property<int>("ilceId")
                        .HasColumnType("integer");

                    b.Property<string>("mahalleAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("mahalleId");

                    b.HasIndex("ilceId");

                    b.ToTable("Mahalle");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Tasinmaz", b =>
                {
                    b.Property<int>("tasinmazId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("tasinmazId"));

                    b.Property<string>("adaa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ilId")
                        .HasColumnType("integer");

                    b.Property<int>("ilceId")
                        .HasColumnType("integer");

                    b.Property<int>("mahalleId")
                        .HasColumnType("integer");

                    b.Property<string>("nitelik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("parsel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("tasinmazId");

                    b.HasIndex("ilId");

                    b.HasIndex("ilceId");

                    b.HasIndex("mahalleId");

                    b.ToTable("Tasinmaz");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Ilce", b =>
                {
                    b.HasOne("tasinmazYonetimi.Models.Il", "Il")
                        .WithMany("Ilce")
                        .HasForeignKey("ilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Log", b =>
                {
                    b.HasOne("tasinmazYonetimi.Models.Kullanici", "Kullanici")
                        .WithMany("Log")
                        .HasForeignKey("kullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Mahalle", b =>
                {
                    b.HasOne("tasinmazYonetimi.Models.Ilce", "Ilce")
                        .WithMany("Mahalle")
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Tasinmaz", b =>
                {
                    b.HasOne("tasinmazYonetimi.Models.Il", "Il")
                        .WithMany("Tasinmaz")
                        .HasForeignKey("ilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tasinmazYonetimi.Models.Ilce", "Ilce")
                        .WithMany("Tasinmaz")
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tasinmazYonetimi.Models.Mahalle", "Mahalle")
                        .WithMany("Tasinmaz")
                        .HasForeignKey("mahalleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Il");

                    b.Navigation("Ilce");

                    b.Navigation("Mahalle");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Il", b =>
                {
                    b.Navigation("Ilce");

                    b.Navigation("Tasinmaz");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Ilce", b =>
                {
                    b.Navigation("Mahalle");

                    b.Navigation("Tasinmaz");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Kullanici", b =>
                {
                    b.Navigation("Log");
                });

            modelBuilder.Entity("tasinmazYonetimi.Models.Mahalle", b =>
                {
                    b.Navigation("Tasinmaz");
                });
#pragma warning restore 612, 618
        }
    }
}
